# system setup
sudo: required

# setup language
language: go
go:
  - "1.25.x"

install:
  - go install github.com/mattn/goveralls@v0.0.12

script:
  - go test -v -covermode=atomic -coverprofile=coverage.out -race ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
